### ISSUE TITLE
Não consegue comunicar com o leitor

### ISSUE THREAD

**Issue by jorgedferreira** [ldiogoz/aCCinaPDF#1]
O programa não está a conseguir aceder à biblioteca do leitor.
Confirmei e o /usr/local/lib/pteidpkcs11.bundle existe.

OSX 10.11.6
java version "1.8.0_101"
Testado como utilizador normal e como root.

`
Mar 10, 2017 11:55:27 AM | Não foi possível carregar a biblioteca!
Mar 10, 2017 11:55:28 AM | java.security.ProviderException: Library /usr/local/lib/pteidpkcs11.bundle does not exist
	at sun.security.pkcs11.SunPKCS11.<init>(SunPKCS11.java:293)
	at sun.security.pkcs11.SunPKCS11.<init>(SunPKCS11.java:107)
	at controller.CCInstance.loadKeyStoreAndAliases(CCInstance.java:207)
	at view.WorkspacePanel.populateComboBox(WorkspacePanel.java:519)
	at view.WorkspacePanel.access$800(WorkspacePanel.java:99)
	at view.WorkspacePanel$3.run(WorkspacePanel.java:498)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
`

**Comment by jorgedferreira** [comment]
Testei mudar o caminho para a biblioteca para 

`path = "/usr/local/lib/pteidpkcs11.dylib";`

Executei e funcionou.

**Comment by vantunes** [comment]
Em windows 10 acontece o mesmo 
Não encontra os certificados instalados
Como faço para resolver?

**Comment by jorgedferreira** [comment]
@vantunes eu alterei o código e depois compilei de novo o programa.

É ver qual o caminho correcto, alterar no programa e compilar de novo na sua plataforma (windows 10)...
Idealmente esses caminhos em vez de estarem fixos no código deviam ser parte das configurações editáveis pelos utilizadores.

**Comment by vantunes** [comment]
Nao sei como isso se faz
